# Generated by Django 6.1.1 on 2026-09-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
