# Generated by Django 6.1.1 on 2026-09-06 06:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_checkout_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkout_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
