# Generated by Django 6.1.1 on 2026-09-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stock_released',
            field=models.BooleanField(default=False),
        ),
    ]
