# Generated by Django 6.1.1 on 2026-09-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_address_tracking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='tracking_id',
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
