# Generated by Django 6.1.1 on 2026-09-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
